### ISSUE TITLE
Cool library so far! Question on use of NativeWind.

### ISSUE THREAD

**Issue by danharten-sovtech** [Mobilecn-UI/nativecn-ui#2]
Is it viable to do this with NativeWind considering main contributor/creator has moved development to Expo?

See here: https://github.com/marklawlor/nativewind/issues/464

Would be great to see this evolve 🤝

**Comment by carlos-garciamoran** [comment]
Hi @danharten-sovtech, thanks for your feedback! We already use NativeWind.

See `package.json` https://github.com/Mobilecn-UI/nativecn-ui/blob/d11993066a6f945cb8bf01d182380f7615abc63c/package.json#L15

**Comment by danharten-sovtech** [comment]
Thanks! Maybe need to reword additional post. I mean -> is it viable to be using NativeWind currently, if the main contributor is no longer maintaining NativeWind? Considering that he is now working at Expo

**Comment by carlos-garciamoran** [comment]
I would say it's even more viable since now Expo is backing NativeWind. Wouldn't be surprised if they adopted the library under their own org —in the same fashion as expo-router.

Regarding maintenance concerns, the last commit on NativeWind happened [yesterday](https://github.com/marklawlor/nativewind/commit/ecaf615f4809bc3bd8a67b7ed1290c8f5cd61f32). Not bad at all!

If you have any other concerns, let us know. But, I believe we're good on that aspect!
